name: CI Pipeline

on:
    workflow_call:
        inputs:
            python-version:
                description: 'Python version to set up'
                required: false
                type: string
                default: '3.12'

            app_directory:
                description: 'Directory of the application within the repository'
                required: false
                type: string
                default: '.'

jobs:
    clone:
        uses: ./.github/workflows/clone.yml

    setup-runtime:
        needs: clone
        uses: ./.github/workflows/setup-runtime.yml
        with:
            python-version: ${{ inputs.python-version }}
            app_directory: ${{ inputs.app_directory }}

    lint:
        needs: setup-runtime
        uses: ./.github/workflows/lint.yml
        with:
            app_directory: ${{ inputs.app_directory }}


    test:
        needs: setup-runtime
        uses: ./.github/workflows/test.yml
        with:
            app_directory: ${{ inputs.app_directory }}

    security:
        needs: setup-runtime
        uses: ./.github/workflows/security.yml
        with:
            app_directory: ${{ inputs.app_directory }}