name: Clone Application Repository

on:
    workflow_call:
    

jobs:
    clone:
        runs-on: ubuntu-latest

        permissions:
            contents: read

        steps:
            - name: checkout pipeline repo
              uses: actions/checkout@v4
              
            - name: verify clone 
              run: |
                  echo "Workspace: $GITHUB_WORKSPACE"
                  echo "Repository: ${{ github.repository }}"
                  echo "Branch: ${{ github.ref_name}}"
                  ls -la
                  pwd

            - name: Upload source artifactory
              uses: actions/upload-artifact@v4
              with:
                    name: app-source-artifact
                    path: | 
                        .
                    retention-days: 1