name: Clone App Repository

on:
    workflow_call:
        # inputs:
        #     app_repo:
        #         required: true
        #         type: string
        #     app_branch:
        #         required: true
        #         type: string
        
        # secrets:
        #     PIPELINE_PAT_TOKEN:
        #         required: true

jobs:
    clone:
        runs-on: ubuntu-latest

        steps:
            - name: checkout pipeline repo
              uses: actions/checkout@v4
              
            - name: verify clone 
              run: |
                  echo "Current directory: $(pwd)"
                  echo "Listing files:"
                  ls -la