name: Test

on:
    workflow_call:
        inputs:
            app_directory:
                description: 'Directory of the application within the repository'
                required: false
                type: string
                default: '.'

            python-version:
                description: 'Python version to set up'
                required: false
                type: string
                default: "3.12"

jobs:
    test:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ${{ inputs.app_directory }}

        steps:
            - name: Download prepared artifact
              uses: actions/download-artifact@v4
              with:
                name: prepared-source-artifact
                path: .

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ inputs.python-version }}

            - name: Cache pip dependencies
              uses: actions/cache@v4
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles(format('{0}/requirements.txt',inputs.app_directory)) }}
                restore-keys: |
                  ${{ runner.os }}-pip-


            - name: Install dependencies
              run: |
                  pip install --upgrade pip
                  if [ -f requirements.txt ]; then
                   pip install -r requirements.txt
                  fi

            - name: Run tests
              env:
                PYTHONPATH: ${{ github.workspace }}
              run: |
                  pytest -v